apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: upload-to-s3
  namespace: infrastructure
  labels:
    app: upload-to-s3
spec:
  selector:
    matchLabels:
      name: upload-to-s3
  template:
    metadata:
      labels:
        name: upload-to-s3
    spec:
      initContainers:
      - name: set-coredump-permissions
        image: busybox:1.28
        command: ['sh','-c','chown -R  1000:1000 /var/coredump']
        securityContext:
          privileged: true
        volumeMounts:
        - name: coredump
          mountPath: /var/coredump
      containers:
      - name: upload-to-s3
        image: gathertown/upload-to-s3:abcd
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: LOCAL_PATH
          value: "/var/coredump"
        - name: S3_BUCKET
          value: "sfu-coredump"
        - name: AWS_DEFAULT_REGION
          value: "us-east-2"
        - name: AWS_ACCESS_KEY_ID
          value: "__AWS_ACCESS_KEY_ID__"
        - name: AWS_SECRET_ACCESS_KEY
          value: "__AWS_SECRET_ACCESS_KEY__"
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 60Mi
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        volumeMounts:
        - name: coredump
          mountPath: /var/coredump
      volumes:
      - name: coredump
        hostPath:
          path: /var/coredump
          type: DirectoryOrCreate
      nodeSelector:
        nodepool.gather.town/sfu: "true"
